[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.autopep8]
max_line_length = 120

[tool.black]
line-length = 120
target-version = ['py38']

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = 'test'
